# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 623)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(231, 371, 421, 51))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(500, 130, 171, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(700, 110, 121, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_mimo = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_mimo.setObjectName("comboBox_mimo")
        self.comboBox_mimo.addItem("")
        self.comboBox_mimo.addItem("")
        self.comboBox_mimo.addItem("")
        self.comboBox_mimo.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_mimo)
        self.comboBox_morOrder = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_morOrder.setObjectName("comboBox_morOrder")
        self.comboBox_morOrder.addItem("")
        self.comboBox_morOrder.addItem("")
        self.comboBox_morOrder.addItem("")
        self.comboBox_morOrder.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_morOrder)
        self.comboBox_carrierAgreg = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_carrierAgreg.setObjectName("comboBox_carrierAgreg")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.comboBox_carrierAgreg.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_carrierAgreg)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 130, 141, 181))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(336, -10, 191, 130))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_4.setEnabled(False)
        self.radioButton_4.setCheckable(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setCheckable(False)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout.addWidget(self.radioButton_5, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-40, 100, 901, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 336, 871, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(420, 110, 21, 241))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.comboBox_Numerology = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Numerology.setGeometry(QtCore.QRect(190, 210, 38, 25))
        self.comboBox_Numerology.setObjectName("comboBox_Numerology")
        self.comboBox_Numerology.addItem("")
        self.comboBox_Numerology.addItem("")
        self.comboBox_Numerology.addItem("")
        self.comboBox_Numerology.addItem("")
        self.comboBox_Numerology.addItem("")
        self.prbs = QtWidgets.QLineEdit(self.centralwidget)
        self.prbs.setGeometry(QtCore.QRect(190, 270, 142, 25))
        self.prbs.setObjectName("prbs")
        self.maxTputMhz = QtWidgets.QLabel(self.centralwidget)
        self.maxTputMhz.setGeometry(QtCore.QRect(278, 450, 321, 51))
        self.maxTputMhz.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.maxTputMhz.setObjectName("maxTputMhz")
        self.maxTputGhz = QtWidgets.QLabel(self.centralwidget)
        self.maxTputGhz.setGeometry(QtCore.QRect(278, 540, 321, 51))
        self.maxTputGhz.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.maxTputGhz.setObjectName("maxTputGhz")
        self.comboBox_overhead = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_overhead.setGeometry(QtCore.QRect(190, 150, 141, 25))
        self.comboBox_overhead.setObjectName("comboBox_overhead")
        self.comboBox_overhead.addItem("")
        self.comboBox_overhead.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 430, 291, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(300, 520, 291, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(220, 290, 91, 21))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#555753;\">MIMO layers</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#555753;\">Modulation Order</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#555753;\">Carrier Agregation</span></p></body></html>"))
        self.comboBox_mimo.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_mimo.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_mimo.setItemText(2, _translate("MainWindow", "4"))
        self.comboBox_mimo.setItemText(3, _translate("MainWindow", "8"))
        self.comboBox_morOrder.setItemText(0, _translate("MainWindow", "2"))
        self.comboBox_morOrder.setItemText(1, _translate("MainWindow", "4"))
        self.comboBox_morOrder.setItemText(2, _translate("MainWindow", "6"))
        self.comboBox_morOrder.setItemText(3, _translate("MainWindow", "8"))
        self.comboBox_carrierAgreg.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_carrierAgreg.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_carrierAgreg.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_carrierAgreg.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_carrierAgreg.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_carrierAgreg.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_carrierAgreg.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_carrierAgreg.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_carrierAgreg.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_carrierAgreg.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_carrierAgreg.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_carrierAgreg.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_carrierAgreg.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_carrierAgreg.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_carrierAgreg.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_carrierAgreg.setItemText(15, _translate("MainWindow", "16"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#555753;\">Overhead</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#555753;\">Numerology</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#555753;\">Number of RBs</span></p></body></html>"))
        self.checkBox_2.setText(_translate("MainWindow", "FDD"))
        self.radioButton_4.setText(_translate("MainWindow", "&Uplink"))
        self.checkBox_3.setText(_translate("MainWindow", "&TDD"))
        self.radioButton_5.setText(_translate("MainWindow", "Down&link"))
        self.comboBox_Numerology.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_Numerology.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_Numerology.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_Numerology.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_Numerology.setItemText(4, _translate("MainWindow", "4"))
        self.maxTputMhz.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#555753;\"><br/></span></p></body></html>"))
        self.maxTputGhz.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#555753;\"><br/></span></p></body></html>"))
        self.comboBox_overhead.setItemText(0, _translate("MainWindow", "0.14"))
        self.comboBox_overhead.setItemText(1, _translate("MainWindow", "0.18"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#555753;\">Throughput in Mbps</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#555753;\">Throughput in Gbps</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">&lt;max 275&gt;</span></p></body></html>"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

